# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='topics',
            new_name='topic',
        ),
    ]
