# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_charts', '0002_auto_20190924_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='q1', max_length=200),
            preserve_default=False,
        ),
    ]
