# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_charts', '0003_question_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='topic',
            new_name='topics',
        ),
    ]
