# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_user_birthday'),
        ('make_charts', '0005_auto_20190925_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='fail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points_of_failure', to='login_app.User'),
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='make_charts.Resource'),
        ),
        migrations.AlterField(
            model_name='question',
            name='point_of_failure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='make_charts.Fail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='practice_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='make_charts.Practice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='make_charts.Section'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='make_charts.Topic'),
        ),
        migrations.AlterField(
            model_name='section',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='make_charts.Section'),
        ),
    ]
