# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_charts', '0006_auto_20190925_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
