# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_charts', '0007_auto_20190926_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='confidence',
        ),
    ]
