# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_charts', '0008_remove_topic_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='(untitled)', max_length=45)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_of_failure', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='make_charts.Resource'),
        ),
        migrations.AlterField(
            model_name='question',
            name='point_of_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='make_charts.Fail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='practice_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='make_charts.Practice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='make_charts.Section'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='make_charts.Topic'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='section',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='make_charts.Question'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='make_charts.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='make_charts.Section'),
        ),
        migrations.AddField(
            model_name='note',
            name='point_of_failure',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to='make_charts.Fail'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to='make_charts.Tag'),
        ),
    ]
