# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-29 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_charts', '0009_auto_20190929_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='point_of_failure',
            field=models.ManyToManyField(related_name='notes', to='make_charts.Fail'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', to='make_charts.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(related_name='tags', to='make_charts.Question'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='topics',
            field=models.ManyToManyField(related_name='tags', to='make_charts.Topic'),
        ),
    ]
